// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"
)

type User struct {
	ID                int64     `json:"id"`
	PublicID          string    `json:"public_id"`
	Name              string    `json:"name"`
	DeviceID          string    `json:"device_id"`
	PreferredCurrency string    `json:"preferred_currency"`
	CreatedAt         time.Time `json:"created_at"`
}
