// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type City struct {
	ID          int64
	CountryCode string
	CountryName string
	StateCode   string
	StateName   string
	Name        string
	I18nKey     string
	Latitude    sql.NullFloat64
	Longitude   sql.NullFloat64
}

type Country struct {
	CodeIso2       string
	CodeIso3       string
	Name           string
	I18nKey        string
	Currency       string
	CurrencySymbol string
	Region         string
	Nationality    string
	Timezones      sql.NullString
	Latitude       sql.NullFloat64
	Longitude      sql.NullFloat64
	Emoji          sql.NullString
	EmojiU         sql.NullString
}

type State struct {
	ID          int64
	CountryCode string
	StateCode   string
	Name        string
	I18nKey     string
	Type        sql.NullString
	Latitude    sql.NullFloat64
	Longitude   sql.NullFloat64
}
