// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"
)

const findCountryByCode = `-- name: FindCountryByCode :one
SELECT 
  code_iso2 AS Code,
  name AS Name,
  currency AS Currency
FROM countries
WHERE code_iso2 = ?1 LIMIT 1
`

type FindCountryByCodeRow struct {
	Code     string
	Name     string
	Currency string
}

func (q *Queries) FindCountryByCode(ctx context.Context, code string) (FindCountryByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, findCountryByCode, code)
	var i FindCountryByCodeRow
	err := row.Scan(&i.Code, &i.Name, &i.Currency)
	return i, err
}
