// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type PopularTravelCountry struct {
	ID                        int64
	TravelerCountryCode       *string
	DestinationCountryCode    string
	DestinationName           string
	DestinationI18nKey        string
	DestinationCurrency       string
	DestinationCurrencySymbol string
	DestinationEmoji          *string
	Rank                      int64
	Count                     *int64
}

type TravelArea struct {
	ID          int64
	Name        string
	I18nKey     string
	Type        string
	CountryCode string
	Latitude    *float64
	Longitude   *float64
}
